export const FEEDBACK_GENERATOR_SYNC_QUEUE = 'FEEDBACK_GENERATOR_SYNC_QUEUE';
export const FEEDBACK_GENERATOR_SYNC_CREATE = 'FEEDBACK_GENERATOR_SYNC_CREATE';
export const FEEDBACK_GENERATOR_SYNC_CREATE_FILE = 'FEEDBACK_GENERATOR_SYNC_CREATE_FILE';
export const FEEDBACK_GENERATOR_SYNC_UPDATE = 'FEEDBACK_GENERATOR_SYNC_UPDATE';
export const FEEDBACK_GENERATOR_SYNC_UPDATE_FILE = 'FEEDBACK_GENERATOR_SYNC_UPDATE_FILE';
export const FEEDBACK_GENERATOR_SYNC_DELETE = 'FEEDBACK_GENERATOR_SYNC_DELETE';
