
export enum TriggerEvent {
    INTERVAL = 'INTERVAL',
    CRONJOB = 'CRONJOB',
    SUBMISSION_RECEIVED = 'SUBMISSION_RECEIVED',
    SUBMISSION_EVALUATED = 'SUBMISSION_EVALUATED',
    SUBMISSION_ACCEPTED = 'SUBMISSION_ACCEPTED',
    SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
    CHALLENGE_COMPLETED = 'CHALLENGE_COMPLETED',
    CHALLENGE_FAILED = 'CHALLENGE_FAILED',
    REWARD_GRANTED = 'REWARD_GRANTED',
    PLAYER_UPDATED = 'PLAYER_UPDATED',
    POINTS_UPDATED = 'POINTS_UPDATED',
    DUEL_INITIATED = 'DUEL_INITIATED',
    DUEL_INVITATION_RECEIVED = 'DUEL_INVITATION_RECEIVED',
    DUEL_ACCEPTED = 'DUEL_ACCEPTED',
    DUEL_REJECTED = 'DUEL_REJECTED',
    DUEL_COMPLETED = 'DUEL_COMPLETED'
}
