# the builder
FROM node:lts-alpine AS builder

WORKDIR /usr/src/app

RUN apk add --no-cache python make g++

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


# the server
FROM node:lts-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY --from=builder /usr/src/app/dist ./dist

CMD [ "node", "dist/index.js" ]

