version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .env:/app/.env
    depends_on:
      - db
    networks:
      - fgpe-authorkit-api-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - api
    environment:
      - API_HOST=api
      - API_PORT=3000
      - NGINX_SERVER_NAME=_
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80
    networks:
      - fgpe-authorkit-api-network

  db:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gkw\CmTcr0,Yf~oe65pEh^EJ
      MONGO_INITDB_DATABASE: fgpe-authorkit
      MONGO_USERNAME: fgpe
      MONGO_PASSWORD: 3abd5yPMaZjh9HfGPTGSEbkoWFNVVm
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb/data:/data/db
      - ./docker/mongodb/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - fgpe-authorkit-api-network

networks:
  fgpe-authorkit-api-network:
    driver: bridge
