export const TESTSET_SYNC_QUEUE = 'TESTSET_SYNC_QUEUE';
export const TESTSET_SYNC_CREATE = 'TESTSET_SYNC_CREATE';
export const TESTSET_SYNC_UPDATE = 'TESTSET_SYNC_UPDATE';
export const TESTSET_SYNC_DELETE = 'TESTSET_SYNC_DELETE';
