export const TEST_GENERATOR_SYNC_QUEUE = 'TEST_GENERATOR_SYNC_QUEUE';
export const TEST_GENERATOR_SYNC_CREATE = 'TEST_GENERATOR_SYNC_CREATE';
export const TEST_GENERATOR_SYNC_CREATE_FILE = 'TEST_GENERATOR_SYNC_CREATE_FILE';
export const TEST_GENERATOR_SYNC_UPDATE = 'TEST_GENERATOR_SYNC_UPDATE';
export const TEST_GENERATOR_SYNC_UPDATE_FILE = 'TEST_GENERATOR_SYNC_UPDATE_FILE';
export const TEST_GENERATOR_SYNC_DELETE = 'TEST_GENERATOR_SYNC_DELETE';
