
export const PROGRAMMING_LANGUAGE_EXT = {
    '1': ['roff', 'roff_manpage'],
    '2': ['roff', 'roff_manpage'],
    '3': ['roff', 'roff_manpage'],
    '4': ['roff', 'roff_manpage'],
    '5': ['roff', 'roff_manpage'],
    '6': ['roff', 'roff_manpage'],
    '7': ['roff', 'roff_manpage'],
    '8': ['roff', 'roff_manpage'],
    '9': ['roff', 'roff_manpage'],
    'bsl': '1c_enterprise',
    'os': '1c_enterprise',
    '4dm': '4d',
    'abap': 'abap',
    'abnf': 'abnf',
    'asc': ['ags_script', 'asciidoc', 'public_key'],
    'ash': 'ags_script',
    'ampl': 'ampl',
    'mod': ['ampl', 'linux_kernel_module', 'modula-2', 'xml'],
    'g4': 'antlr',
    'apib': 'api_blueprint',
    'apl': 'apl',
    'dyalog': 'apl',
    'asn': 'asn.1',
    'asn1': 'asn.1',
    'asp': 'asp',
    'asax': 'asp',
    'ascx': 'asp',
    'ashx': 'asp',
    'asmx': 'asp',
    'aspx': 'asp',
    'axd': 'asp',
    'dats': 'ats',
    'hats': 'ats',
    'sats': 'ats',
    'as': ['actionscript', 'angelscript'],
    'adb': 'ada',
    'ada': 'ada',
    'ads': 'ada',
    'afm': 'adobe_font_metrics',
    'agda': 'agda',
    'als': 'alloy',
    'OutJob': 'altium_designer',
    'PcbDoc': 'altium_designer',
    'PrjPCB': 'altium_designer',
    'SchDoc': 'altium_designer',
    'angelscript': 'angelscript',
    'apacheconf': 'apacheconf',
    'vhost': ['apacheconf', 'nginx'],
    'cls': ['apex', 'objectscript', 'openedge_abl', 'tex', 'vba'],
    'agc': 'apollo_guidance_computer',
    'applescript': 'applescript',
    'scpt': 'applescript',
    'arc': 'arc',
    'asciidoc': 'asciidoc',
    'adoc': 'asciidoc',
    'aj': 'aspectj',
    'asm': ['assembly', 'motorola_68k_assembly'],
    'a51': 'assembly',
    'i': ['assembly', 'motorola_68k_assembly', 'swig'],
    'inc': ['assembly', 'c++', 'html', 'motorola_68k_assembly', 'nasl', 'php', 'pov-ray_sdl', 'pascal', 'pawn', 'sql', 'sourcepawn'],
    'nasm': 'assembly',
    'asy': ['asymptote', 'ltspice_symbol'],
    'aug': 'augeas',
    'ahk': 'autohotkey',
    'ahkl': 'autohotkey',
    'au3': 'autoit',
    'awk': 'awk',
    'auk': 'awk',
    'gawk': 'awk',
    'mawk': 'awk',
    'nawk': 'awk',
    'bal': 'ballerina',
    'bat': 'batchfile',
    'cmd': 'batchfile',
    'befunge': 'befunge',
    'bib': 'bibtex',
    'bibtex': 'bibtex',
    'bison': 'bison',
    'bb': ['bitbake', 'blitzbasic'],
    'blade': 'blade',
    'blade.php': 'blade',
    'decls': 'blitzbasic',
    'bmx': 'blitzmax',
    'bsv': 'bluespec',
    'boo': 'boo',
    'b': ['brainfuck', 'limbo'],
    'bf': ['brainfuck', 'hyphy'],
    'brs': 'brightscript',
    'c': 'c',
    'cats': 'c',
    'h': ['c', 'c++', 'objective-c'],
    'idc': 'c',
    'cs': ['c#', 'smalltalk'],
    'cake': ['c#', 'coffeescript'],
    'csx': 'c#',
    'linq': 'c#',
    'cpp': 'c++',
    'c++': 'c++',
    'cc': 'c++',
    'cp': ['c++', 'component_pascal'],
    'cxx': 'c++',
    'h++': 'c++',
    'hh': ['c++', 'hack'],
    'hpp': 'c++',
    'hxx': 'c++',
    'inl': 'c++',
    'ino': 'c++',
    'ipp': 'c++',
    're': ['c++', 'reason'],
    'tcc': 'c++',
    'tpp': 'c++',
    'c-objdump': 'c-objdump',
    'chs': 'c2hs_haskell',
    'clp': 'clips',
    'cmake': 'cmake',
    'cmake.in': 'cmake',
    'cob': 'cobol',
    'cbl': 'cobol',
    'ccp': 'cobol',
    'cobol': 'cobol',
    'cpy': 'cobol',
    'dae': 'collada',
    'cson': 'cson',
    'css': 'css',
    'csv': 'csv',
    'w': ['cweb', 'openedge_abl'],
    'cabal': 'cabal_config',
    'capnp': 'cap\'n_proto',
    'mss': 'cartocss',
    'ceylon': 'ceylon',
    'chpl': 'chapel',
    'ch': ['charity', 'xbase'],
    'ck': 'chuck',
    'cirru': 'cirru',
    'clw': 'clarion',
    'icl': 'clean',
    'dcl': 'clean',
    'click': 'click',
    'clj': 'clojure',
    'boot': 'clojure',
    'cl2': 'clojure',
    'cljc': 'clojure',
    'cljs': 'clojure',
    'cljs.hl': 'clojure',
    'cljscm': 'clojure',
    'cljx': 'clojure',
    'hic': 'clojure',
    'soy': 'closure_templates',
    'conllu': 'conll-u',
    'conll': 'conll-u',
    'ql': 'codeql',
    'qll': 'codeql',
    'coffee': 'coffeescript',
    '_coffee': 'coffeescript',
    'cjsx': 'coffeescript',
    'iced': 'coffeescript',
    'cfm': 'coldfusion',
    'cfml': 'coldfusion',
    'cfc': 'coldfusion_cfc',
    'lisp': ['common_lisp', 'newlisp'],
    'asd': 'common_lisp',
    'cl': ['common_lisp', 'cool', 'opencl'],
    'l': ['common_lisp', 'lex', 'picolisp', 'roff'],
    'lsp': ['common_lisp', 'newlisp'],
    'ny': 'common_lisp',
    'podsl': 'common_lisp',
    'sexp': 'common_lisp',
    'cwl': 'common_workflow_language',
    'cps': 'component_pascal',
    'coq': 'coq',
    'v': ['coq', 'v', 'verilog'],
    'cppobjdump': 'cpp-objdump',
    'c++-objdump': 'cpp-objdump',
    'c++objdump': 'cpp-objdump',
    'cpp-objdump': 'cpp-objdump',
    'cxx-objdump': 'cpp-objdump',
    'creole': 'creole',
    'cr': 'crystal',
    'orc': 'csound',
    'udo': 'csound',
    'csd': 'csound_document',
    'sco': 'csound_score',
    'cu': 'cuda',
    'cuh': 'cuda',
    'cy': 'cycript',
    'pyx': 'cython',
    'pxd': 'cython',
    'pxi': 'cython',
    'd': ['d', 'dtrace', 'makefile'],
    'di': 'd',
    'd-objdump': 'd-objdump',
    'com': 'digital_command_language',
    'dm': 'dm',
    'zone': 'dns_zone',
    'arpa': 'dns_zone',
    'dfy': 'dafny',
    'darcspatch': 'darcs_patch',
    'dpatch': 'darcs_patch',
    'dart': 'dart',
    'dwl': 'dataweave',
    'dhall': 'dhall',
    'diff': 'diff',
    'patch': 'diff',
    'x': ['directx_3d_file', 'linker_script', 'logos', 'rpc'],
    'dockerfile': 'dockerfile',
    'djs': 'dogescript',
    'dylan': 'dylan',
    'dyl': 'dylan',
    'intr': 'dylan',
    'lid': 'dylan',
    'E': 'e',
    'ebnf': 'ebnf',
    'ecl': ['ecl', 'eclipse'],
    'eclxml': 'ecl',
    'ejs': 'ejs',
    'eml': 'eml',
    'mbox': 'eml',
    'eq': 'eq',
    'sch': ['eagle', 'kicad_schematic', 'scheme', 'xml'],
    'brd': ['eagle', 'kicad_legacy_layout'],
    'eb': 'easybuild',
    'epj': 'ecere_projects',
    'edc': 'edje_data_collection',
    'e': 'eiffel',
    'ex': 'elixir',
    'exs': 'elixir',
    'elm': 'elm',
    'el': 'emacs_lisp',
    'emacs': 'emacs_lisp',
    'emacs.desktop': 'emacs_lisp',
    'em': 'emberscript',
    'emberscript': 'emberscript',
    'erl': 'erlang',
    'app.src': 'erlang',
    'es': ['erlang', 'javascript'],
    'escript': 'erlang',
    'hrl': 'erlang',
    'xrl': 'erlang',
    'yrl': 'erlang',
    'fs': ['f#', 'filterscript', 'forth', 'glsl'],
    'fsi': 'f#',
    'fsx': 'f#',
    'fst': 'f*',
    'flf': 'figlet_font',
    'fx': ['flux', 'hlsl'],
    'flux': 'flux',
    'factor': 'factor',
    'fy': 'fancy',
    'fancypack': 'fancy',
    'fan': 'fantom',
    'dsp': ['faust', 'microsoft_developer_studio_project'],
    'f': ['filebench_wml', 'forth', 'fortran'],
    'for': ['formatted', 'forth', 'fortran'],
    'eam.fs': 'formatted',
    'fth': 'forth',
    '4th': 'forth',
    'forth': 'forth',
    'fr': ['forth', 'frege', 'text'],
    'frt': 'forth',
    'f77': 'fortran',
    'fpp': 'fortran',
    'f90': 'fortran_free_form',
    'f03': 'fortran_free_form',
    'f08': 'fortran_free_form',
    'f95': 'fortran_free_form',
    'ftl': 'freemarker',
    'fut': 'futhark',
    'g': ['g-code', 'gap'],
    'cnc': 'g-code',
    'gco': 'g-code',
    'gcode': 'g-code',
    'gaml': 'gaml',
    'gms': 'gams',
    'gap': 'gap',
    'gd': ['gap', 'gdscript'],
    'gi': 'gap',
    'tst': ['gap', 'scilab'],
    'md': ['gcc_machine_description', 'markdown'],
    'gdb': 'gdb',
    'gdbinit': 'gdb',
    'ged': 'gedcom',
    'glsl': 'glsl',
    'fp': 'glsl',
    'frag': ['glsl', 'javascript'],
    'frg': 'glsl',
    'fsh': 'glsl',
    'fshader': 'glsl',
    'geo': 'glsl',
    'geom': 'glsl',
    'glslf': 'glsl',
    'glslv': 'glsl',
    'gs': ['glsl', 'genie', 'gosu', 'javascript'],
    'gshader': 'glsl',
    'shader': ['glsl', 'shaderlab'],
    'tesc': 'glsl',
    'tese': 'glsl',
    'vert': 'glsl',
    'vrx': 'glsl',
    'vsh': 'glsl',
    'vshader': 'glsl',
    'gn': 'gn',
    'gni': 'gn',
    'gml': ['game_maker_language', 'gerber_image', 'graph_modeling_language', 'xml'],
    'kid': 'genshi',
    'ebuild': 'gentoo_ebuild',
    'eclass': 'gentoo_eclass',
    'gbr': 'gerber_image',
    'gbl': 'gerber_image',
    'gbo': 'gerber_image',
    'gbp': 'gerber_image',
    'gbs': 'gerber_image',
    'gko': 'gerber_image',
    'gpb': 'gerber_image',
    'gpt': 'gerber_image',
    'gtl': 'gerber_image',
    'gto': 'gerber_image',
    'gtp': 'gerber_image',
    'gts': 'gerber_image',
    'po': 'gettext_catalog',
    'pot': 'gettext_catalog',
    'feature': 'gherkin',
    'gitconfig': 'git_config',
    'glf': 'glyph',
    'bdf': 'glyph_bitmap_distribution_format',
    'gp': 'gnuplot',
    'gnu': 'gnuplot',
    'gnuplot': 'gnuplot',
    'p': ['gnuplot', 'openedge_abl'],
    'plot': 'gnuplot',
    'plt': 'gnuplot',
    'go': 'go',
    'golo': 'golo',
    'gst': 'gosu',
    'gsx': 'gosu',
    'vark': 'gosu',
    'grace': 'grace',
    'gradle': 'gradle',
    'gf': 'grammatical_framework',
    'graphql': 'graphql',
    'gql': 'graphql',
    'graphqls': 'graphql',
    'dot': 'graphviz_(dot)',
    'gv': 'graphviz_(dot)',
    'groovy': 'groovy',
    'grt': 'groovy',
    'gtpl': 'groovy',
    'gvy': 'groovy',
    'gsp': 'groovy_server_pages',
    'cfg': ['haproxy', 'ini'],
    'hcl': 'hcl',
    'tf': 'hcl',
    'tfvars': 'hcl',
    'workflow': ['hcl', 'xml'],
    'hlsl': 'hlsl',
    'cginc': 'hlsl',
    'fxh': 'hlsl',
    'hlsli': 'hlsl',
    'html': 'html',
    'htm': 'html',
    'html.hl': 'html',
    'st': ['html', 'smalltalk'],
    'xht': 'html',
    'xhtml': 'html',
    'jinja': 'html+django',
    'jinja2': 'html+django',
    'mustache': 'html+django',
    'njk': 'html+django',
    'ecr': 'html+ecr',
    'eex': 'html+eex',
    'erb': 'html+erb',
    'erb.deface': 'html+erb',
    'phtml': 'html+php',
    'cshtml': 'html+razor',
    'razor': 'html+razor',
    'http': 'http',
    'hxml': 'hxml',
    'hack': 'hack',
    'hhi': 'hack',
    'php': ['hack', 'php'],
    'haml': 'haml',
    'haml.deface': 'haml',
    'handlebars': 'handlebars',
    'hbs': 'handlebars',
    'hb': 'harbour',
    'hs': 'haskell',
    'hs-boot': 'haskell',
    'hsc': 'haskell',
    'hx': 'haxe',
    'hxsl': 'haxe',
    'q': ['hiveql', 'q'],
    'hql': 'hiveql',
    'hc': 'holyc',
    'hy': 'hy',
    'pro': ['idl', 'ini', 'proguard', 'prolog', 'qmake'],
    'dlm': 'idl',
    'ipf': 'igor_pro',
    'ini': 'ini',
    'dof': 'ini',
    'lektorproject': 'ini',
    'prefs': 'ini',
    'properties': ['ini', 'java_properties'],
    'irclog': 'irc_log',
    'weechatlog': 'irc_log',
    'idr': 'idris',
    'lidr': 'idris',
    'gitignore': 'ignore_list',
    'ni': 'inform_7',
    'i7x': 'inform_7',
    'iss': 'inno_setup',
    'isl': 'inno_setup',
    'io': 'io',
    'ik': 'ioke',
    'thy': 'isabelle',
    'ijs': 'j',
    'flex': 'jflex',
    'jflex': 'jflex',
    'json': 'json',
    'avsc': 'json',
    'geojson': 'json',
    'gltf': 'json',
    'har': 'json',
    'ice': ['json', 'slice'],
    'JSON-tmLanguage': 'json',
    'jsonl': 'json',
    'mcmeta': 'json',
    'tfstate': 'json',
    'tfstate.backup': 'json',
    'topojson': 'json',
    'webapp': 'json',
    'webmanifest': 'json',
    'yy': ['json', 'yacc'],
    'yyp': 'json',
    'jsonc': 'json_with_comments',
    'sublime-build': 'json_with_comments',
    'sublime-commands': 'json_with_comments',
    'sublime-completions': 'json_with_comments',
    'sublime-keymap': 'json_with_comments',
    'sublime-macro': 'json_with_comments',
    'sublime-menu': 'json_with_comments',
    'sublime-mousemap': 'json_with_comments',
    'sublime-project': 'json_with_comments',
    'sublime-settings': 'json_with_comments',
    'sublime-theme': 'json_with_comments',
    'sublime-workspace': 'json_with_comments',
    'sublime_metrics': 'json_with_comments',
    'sublime_session': 'json_with_comments',
    'json5': 'json5',
    'jsonld': 'jsonld',
    'jq': 'jsoniq',
    'jsx': 'jsx',
    'j': ['jasmin', 'objective-j'],
    'java': 'java',
    'jsp': 'java_server_pages',
    'js': 'javascript',
    '_js': 'javascript',
    'bones': 'javascript',
    'cjs': 'javascript',
    'es6': 'javascript',
    'jake': 'javascript',
    'jsb': 'javascript',
    'jscad': 'javascript',
    'jsfl': 'javascript',
    'jsm': 'javascript',
    'jss': 'javascript',
    'mjs': 'javascript',
    'njs': 'javascript',
    'pac': 'javascript',
    'sjs': 'javascript',
    'ssjs': 'javascript',
    'xsjs': 'javascript',
    'xsjslib': 'javascript',
    'js.erb': 'javascript+erb',
    'jison': 'jison',
    'jisonlex': 'jison_lex',
    'ol': 'jolie',
    'iol': 'jolie',
    'jsonnet': 'jsonnet',
    'libsonnet': 'jsonnet',
    'jl': 'julia',
    'ipynb': 'jupyter_notebook',
    'krl': 'krl',
    'ksy': 'kaitai_struct',
    'kicad_pcb': 'kicad_layout',
    'kicad_mod': 'kicad_layout',
    'kicad_wks': 'kicad_layout',
    'kit': 'kit',
    'kt': 'kotlin',
    'ktm': 'kotlin',
    'kts': 'kotlin',
    'lfe': 'lfe',
    'll': 'llvm',
    'lol': 'lolcode',
    'lsl': 'lsl',
    'lslp': 'lsl',
    'lvproj': 'labview',
    'lasso': 'lasso',
    'las': 'lasso',
    'lasso8': 'lasso',
    'lasso9': 'lasso',
    'latte': 'latte',
    'lean': 'lean',
    'hlean': 'lean',
    'less': 'less',
    'lex': 'lex',
    'ly': 'lilypond',
    'ily': 'lilypond',
    'm': ['limbo', 'm', 'matlab', 'muf', 'mathematica', 'mercury', 'objective-c'],
    'ld': 'linker_script',
    'lds': 'linker_script',
    'liquid': 'liquid',
    'lagda': 'literate_agda',
    'litcoffee': 'literate_coffeescript',
    'lhs': 'literate_haskell',
    'ls': ['livescript', 'loomscript'],
    '_ls': 'livescript',
    'xm': 'logos',
    'xi': 'logos',
    'lgt': 'logtalk',
    'logtalk': 'logtalk',
    'lookml': 'lookml',
    'model.lkml': 'lookml',
    'view.lkml': 'lookml',
    'lua': 'lua',
    'fcgi': ['lua', 'php', 'perl', 'python', 'ruby', 'shell'],
    'nse': 'lua',
    'p8': 'lua',
    'pd_lua': 'lua',
    'rbxs': 'lua',
    'rockspec': 'lua',
    'wlua': 'lua',
    'mumps': 'm',
    'm4': ['m4', 'm4sugar'],
    'matlab': 'matlab',
    'ms': ['maxscript', 'roff', 'unix_assembly'],
    'mcr': 'maxscript',
    'mlir': 'mlir',
    'mq4': 'mql4',
    'mqh': ['mql4', 'mql5'],
    'mq5': 'mql5',
    'mtml': 'mtml',
    'muf': 'muf',
    'm2': 'macaulay2',
    'mak': 'makefile',
    'make': 'makefile',
    'mk': 'makefile',
    'mkfile': 'makefile',
    'mako': 'mako',
    'mao': 'mako',
    'markdown': 'markdown',
    'mdown': 'markdown',
    'mdwn': 'markdown',
    'mdx': 'markdown',
    'mkd': 'markdown',
    'mkdn': 'markdown',
    'mkdown': 'markdown',
    'ronn': 'markdown',
    'workbook': 'markdown',
    'marko': 'marko',
    'mask': ['mask', 'unity3d_asset'],
    'mathematica': 'mathematica',
    'cdf': 'mathematica',
    'ma': 'mathematica',
    'mt': 'mathematica',
    'nb': ['mathematica', 'text'],
    'nbp': 'mathematica',
    'wl': 'mathematica',
    'wlt': 'mathematica',
    'maxpat': 'max',
    'maxhelp': 'max',
    'maxproj': 'max',
    'mxt': 'max',
    'pat': 'max',
    'mediawiki': 'mediawiki',
    'wiki': 'mediawiki',
    'moo': ['mercury', 'moocode'],
    'metal': 'metal',
    'minid': 'minid',
    'druby': 'mirah',
    'duby': 'mirah',
    'mirah': 'mirah',
    'mo': 'modelica',
    'i3': 'modula-3',
    'ig': 'modula-3',
    'm3': 'modula-3',
    'mg': 'modula-3',
    'mms': 'module_management_system',
    'mmk': 'module_management_system',
    'monkey': 'monkey',
    'monkey2': 'monkey',
    'moon': 'moonscript',
    's': ['motorola_68k_assembly', 'unix_assembly'],
    'x68': 'motorola_68k_assembly',
    'muse': 'muse',
    'myt': 'myghty',
    'nasl': 'nasl',
    'ncl': ['ncl', 'text', 'xml'],
    'neon': 'neon',
    'nl': ['nl', 'newlisp'],
    'nsi': 'nsis',
    'nsh': 'nsis',
    'ne': 'nearley',
    'nearley': 'nearley',
    'n': ['nemerle', 'roff'],
    'axs': 'netlinx',
    'axi': 'netlinx',
    'axs.erb': 'netlinx+erb',
    'axi.erb': 'netlinx+erb',
    'nlogo': 'netlogo',
    'nf': 'nextflow',
    'nginxconf': 'nginx',
    'nim': 'nim',
    'nim.cfg': 'nim',
    'nimble': 'nim',
    'nimrod': 'nim',
    'nims': 'nim',
    'ninja': 'ninja',
    'nit': 'nit',
    'nix': 'nix',
    'nu': 'nu',
    'numpy': 'numpy',
    'numpyw': 'numpy',
    'numsc': 'numpy',
    'ml': 'ocaml',
    'eliom': 'ocaml',
    'eliomi': 'ocaml',
    'ml4': 'ocaml',
    'mli': 'ocaml',
    'mll': 'ocaml',
    'mly': 'ocaml',
    'objdump': 'objdump',
    'odin': ['object_data_instance_notation', 'odin'],
    'mm': ['objective-c++', 'xml'],
    'sj': 'objective-j',
    'omgrofl': 'omgrofl',
    'opa': 'opa',
    'opal': 'opal',
    'rego': 'open_policy_agent',
    'opencl': 'opencl',
    'qasm': 'openqasm',
    'scad': 'openscad',
    'plist': ['openstep_property_list', 'xml_property_list'],
    'fea': 'opentype_feature_file',
    'org': 'org',
    'ox': 'ox',
    'oxh': 'ox',
    'oxo': 'ox',
    'oxygene': 'oxygene',
    'oz': 'oz',
    'p4': 'p4',
    'aw': 'php',
    'ctp': 'php',
    'php3': 'php',
    'php4': 'php',
    'php5': 'php',
    'phps': 'php',
    'phpt': 'php',
    'pls': 'plsql',
    'bdy': 'plsql',
    'ddl': ['plsql', 'sql'],
    'fnc': 'plsql',
    'pck': 'plsql',
    'pkb': 'plsql',
    'pks': 'plsql',
    'plb': 'plsql',
    'plsql': 'plsql',
    'prc': ['plsql', 'sql'],
    'spc': 'plsql',
    'sql': ['plsql', 'plpgsql', 'sql', 'sqlpl', 'tsql'],
    'tpb': 'plsql',
    'tps': 'plsql',
    'trg': 'plsql',
    'vw': 'plsql',
    'pgsql': 'plpgsql',
    'pov': 'pov-ray_sdl',
    'pan': 'pan',
    'psc': 'papyrus',
    'parrot': 'parrot',
    'pasm': 'parrot_assembly',
    'pir': 'parrot_internal_representation',
    'pas': 'pascal',
    'dfm': 'pascal',
    'dpr': 'pascal',
    'lpr': 'pascal',
    'pascal': 'pascal',
    'pp': ['pascal', 'puppet'],
    'pwn': 'pawn',
    'sma': 'pawn',
    'pep': 'pep8',
    'pl': ['perl', 'prolog', 'raku'],
    'al': 'perl',
    'cgi': ['perl', 'python', 'shell'],
    'perl': 'perl',
    'ph': 'perl',
    'plx': 'perl',
    'pm': ['perl', 'raku', 'x_pixmap'],
    'psgi': 'perl',
    't': ['perl', 'raku', 'terra', 'turing'],
    'pic': 'pic',
    'chem': 'pic',
    'pkl': 'pickle',
    'pig': 'piglatin',
    'pike': 'pike',
    'pmod': 'pike',
    'puml': 'plantuml',
    'iuml': 'plantuml',
    'plantuml': 'plantuml',
    'pod': ['pod', 'pod_6'],
    'pod6': 'pod_6',
    'pogo': 'pogoscript',
    'pony': 'pony',
    'pcss': 'postcss',
    'postcss': 'postcss',
    'ps': 'postscript',
    'eps': 'postscript',
    'epsi': 'postscript',
    'pfa': 'postscript',
    'pbt': 'powerbuilder',
    'sra': 'powerbuilder',
    'sru': 'powerbuilder',
    'srw': 'powerbuilder',
    'ps1': 'powershell',
    'psd1': 'powershell',
    'psm1': 'powershell',
    'prisma': 'prisma',
    'pde': 'processing',
    'prolog': 'prolog',
    'yap': 'prolog',
    'spin': 'propeller_spin',
    'proto': 'protocol_buffer',
    'pub': 'public_key',
    'jade': 'pug',
    'pug': 'pug',
    'pd': 'pure_data',
    'pb': 'purebasic',
    'pbi': 'purebasic',
    'purs': 'purescript',
    'py': 'python',
    'gyp': 'python',
    'gypi': 'python',
    'lmi': 'python',
    'py3': 'python',
    'pyde': 'python',
    'pyi': 'python',
    'pyp': 'python',
    'pyt': 'python',
    'pyw': 'python',
    'rpy': ['python', 'ren\'py'],
    'smk': 'python',
    'spec': ['python', 'rpm_spec', 'ruby'],
    'tac': 'python',
    'wsgi': 'python',
    'xpy': 'python',
    'pytb': 'python_traceback',
    'qs': ['q#', 'qt_script'],
    'qml': 'qml',
    'qbs': 'qml',
    'pri': 'qmake',
    'r': ['r', 'rebol'],
    'rd': 'r',
    'rsx': 'r',
    'raml': 'raml',
    'rdoc': 'rdoc',
    'rbbas': 'realbasic',
    'rbfrm': 'realbasic',
    'rbmnu': 'realbasic',
    'rbres': 'realbasic',
    'rbtbar': 'realbasic',
    'rbuistate': 'realbasic',
    'rexx': 'rexx',
    'pprx': 'rexx',
    'rex': 'rexx',
    'rhtml': 'rhtml',
    'rmd': 'rmarkdown',
    'rnh': 'runoff',
    'rno': ['runoff', 'roff'],
    'rkt': 'racket',
    'rktd': 'racket',
    'rktl': 'racket',
    'scrbl': 'racket',
    'rl': 'ragel',
    '6pl': 'raku',
    '6pm': 'raku',
    'nqp': 'raku',
    'p6': 'raku',
    'p6l': 'raku',
    'p6m': 'raku',
    'pl6': 'raku',
    'pm6': 'raku',
    'rsc': 'rascal',
    'raw': 'raw_token_data',
    'rei': 'reason',
    'reb': 'rebol',
    'r2': 'rebol',
    'r3': 'rebol',
    'rebol': 'rebol',
    'red': 'red',
    'reds': 'red',
    'cw': 'redcode',
    'regexp': 'regular_expression',
    'regex': 'regular_expression',
    'rs': ['renderscript', 'rust'],
    'rsh': 'renderscript',
    'rtf': 'rich_text_format',
    'ring': 'ring',
    'riot': 'riot',
    'robot': 'robotframework',
    'roff': 'roff',
    '1in': ['roff', 'roff_manpage'],
    '1m': ['roff', 'roff_manpage'],
    '1x': ['roff', 'roff_manpage'],
    '3in': ['roff', 'roff_manpage'],
    '3m': ['roff', 'roff_manpage'],
    '3p': ['roff', 'roff_manpage'],
    '3pm': ['roff', 'roff_manpage'],
    '3qt': ['roff', 'roff_manpage'],
    '3x': ['roff', 'roff_manpage'],
    'man': ['roff', 'roff_manpage'],
    'mdoc': ['roff', 'roff_manpage'],
    'me': 'roff',
    'nr': 'roff',
    'tmac': 'roff',
    'rg': 'rouge',
    'rb': 'ruby',
    'builder': 'ruby',
    'eye': 'ruby',
    'gemspec': 'ruby',
    'god': 'ruby',
    'jbuilder': 'ruby',
    'mspec': 'ruby',
    'pluginspec': ['ruby', 'xml'],
    'podspec': 'ruby',
    'rabl': 'ruby',
    'rake': 'ruby',
    'rbi': 'ruby',
    'rbuild': 'ruby',
    'rbw': 'ruby',
    'rbx': 'ruby',
    'ru': 'ruby',
    'ruby': 'ruby',
    'thor': 'ruby',
    'watchr': 'ruby',
    'rs.in': 'rust',
    'sas': 'sas',
    'scss': 'scss',
    'smt2': 'smt',
    'smt': 'smt',
    'sparql': 'sparql',
    'rq': 'sparql',
    'sqf': 'sqf',
    'hqf': 'sqf',
    'cql': 'sql',
    'mysql': 'sql',
    'tab': 'sql',
    'udf': 'sql',
    'viw': 'sql',
    'db2': 'sqlpl',
    'srt': ['srecode_template', 'subrip_text'],
    'ston': 'ston',
    'svg': 'svg',
    'sage': 'sage',
    'sagews': 'sage',
    'sls': ['saltstack', 'scheme'],
    'sass': 'sass',
    'scala': 'scala',
    'kojo': 'scala',
    'sbt': 'scala',
    'sc': ['scala', 'supercollider'],
    'scaml': 'scaml',
    'scm': 'scheme',
    'sld': 'scheme',
    'sps': 'scheme',
    'ss': 'scheme',
    'sci': 'scilab',
    'sce': 'scilab',
    'self': 'self',
    'sh': 'shell',
    'bash': 'shell',
    'bats': 'shell',
    'command': 'shell',
    'ksh': 'shell',
    'sh.in': 'shell',
    'tmux': 'shell',
    'tool': 'shell',
    'zsh': 'shell',
    'sh-session': 'shellsession',
    'shen': 'shen',
    'sieve': 'sieve',
    'sl': 'slash',
    'slim': 'slim',
    'cocci': 'smpl',
    'smali': 'smali',
    'tpl': 'smarty',
    'sp': 'sourcepawn',
    'sfd': 'spline_font_database',
    'nut': 'squirrel',
    'stan': 'stan',
    'ML': 'standard_ml',
    'fun': 'standard_ml',
    'sig': 'standard_ml',
    'sml': 'standard_ml',
    'bzl': 'starlark',
    'do': 'stata',
    'ado': 'stata',
    'doh': 'stata',
    'ihlp': 'stata',
    'mata': 'stata',
    'matah': 'stata',
    'sthlp': 'stata',
    'styl': 'stylus',
    'sss': 'sugarss',
    'scd': 'supercollider',
    'svelte': 'svelte',
    'swift': 'swift',
    'sv': 'systemverilog',
    'svh': 'systemverilog',
    'vh': 'systemverilog',
    '8xp': 'ti_program',
    '8xk': 'ti_program',
    '8xk.txt': 'ti_program',
    '8xp.txt': 'ti_program',
    'tla': 'tla',
    'toml': 'toml',
    'tsx': ['tsx', 'xml'],
    'txl': 'txl',
    'tcl': 'tcl',
    'adp': 'tcl',
    'tm': 'tcl',
    'tcsh': 'tcsh',
    'csh': 'tcsh',
    'tex': 'tex',
    'aux': 'tex',
    'bbx': 'tex',
    'cbx': 'tex',
    'dtx': 'tex',
    'ins': 'tex',
    'lbx': 'tex',
    'ltx': 'tex',
    'mkii': 'tex',
    'mkiv': 'tex',
    'mkvi': 'tex',
    'sty': 'tex',
    'toc': ['tex', 'world_of_warcraft_addon_data'],
    'tea': 'tea',
    'texinfo': 'texinfo',
    'texi': 'texinfo',
    'txi': 'texinfo',
    'txt': 'text',
    'no': 'text',
    'textile': 'textile',
    'thrift': 'thrift',
    'tu': 'turing',
    'ttl': 'turtle',
    'twig': 'twig',
    'tl': 'type_language',
    'ts': ['typescript', 'xml'],
    'upc': 'unified_parallel_c',
    'anim': 'unity3d_asset',
    'asset': 'unity3d_asset',
    'mat': 'unity3d_asset',
    'meta': 'unity3d_asset',
    'prefab': 'unity3d_asset',
    'unity': 'unity3d_asset',
    'uno': 'uno',
    'uc': 'unrealscript',
    'ur': 'urweb',
    'urs': 'urweb',
    'bas': 'vba',
    'frm': 'vba',
    'frx': 'vba',
    'vba': ['vba', 'vim_script'],
    'vbs': 'vbscript',
    'vcl': 'vcl',
    'vhdl': 'vhdl',
    'vhd': 'vhdl',
    'vhf': 'vhdl',
    'vhi': 'vhdl',
    'vho': 'vhdl',
    'vhs': 'vhdl',
    'vht': 'vhdl',
    'vhw': 'vhdl',
    'vala': 'vala',
    'vapi': 'vala',
    'veo': 'verilog',
    'snip': 'vim_snippet',
    'snippet': 'vim_snippet',
    'snippets': 'vim_snippet',
    'vim': 'vim_script',
    'vmb': 'vim_script',
    'vb': 'visual_basic_.net',
    'vbhtml': 'visual_basic_.net',
    'volt': 'volt',
    'vue': 'vue',
    'mtl': 'wavefront_material',
    'obj': 'wavefront_object',
    'owl': 'web_ontology_language',
    'wast': 'webassembly',
    'wat': 'webassembly',
    'webidl': 'webidl',
    'vtt': 'webvtt',
    'reg': 'windows_registry_entries',
    'wlk': 'wollok',
    'xbm': 'x_bitmap',
    'xpm': 'x_pixmap',
    'x10': 'x10',
    'xc': 'xc',
    'xml': 'xml',
    'adml': 'xml',
    'admx': 'xml',
    'ant': 'xml',
    'axml': 'xml',
    'builds': 'xml',
    'ccproj': 'xml',
    'ccxml': 'xml',
    'clixml': 'xml',
    'cproject': 'xml',
    'cscfg': 'xml',
    'csdef': 'xml',
    'csl': 'xml',
    'csproj': 'xml',
    'ct': 'xml',
    'depproj': 'xml',
    'dita': 'xml',
    'ditamap': 'xml',
    'ditaval': 'xml',
    'dll.config': 'xml',
    'dotsettings': 'xml',
    'filters': 'xml',
    'fsproj': 'xml',
    'fxml': 'xml',
    'glade': 'xml',
    'gmx': 'xml',
    'grxml': 'xml',
    'iml': 'xml',
    'ivy': 'xml',
    'jelly': 'xml',
    'jsproj': 'xml',
    'kml': 'xml',
    'launch': 'xml',
    'mdpolicy': 'xml',
    'mjml': 'xml',
    'mxml': 'xml',
    'natvis': 'xml',
    'ndproj': 'xml',
    'nproj': 'xml',
    'nuspec': 'xml',
    'odd': 'xml',
    'osm': 'xml',
    'pkgproj': 'xml',
    'proj': 'xml',
    'props': 'xml',
    'ps1xml': 'xml',
    'psc1': 'xml',
    'pt': 'xml',
    'rdf': 'xml',
    'resx': 'xml',
    'rss': 'xml',
    'scxml': 'xml',
    'sfproj': 'xml',
    'shproj': 'xml',
    'srdf': 'xml',
    'storyboard': 'xml',
    'sublime-snippet': 'xml',
    'targets': 'xml',
    'tml': 'xml',
    'ui': 'xml',
    'urdf': 'xml',
    'ux': 'xml',
    'vbproj': 'xml',
    'vcxproj': 'xml',
    'vsixmanifest': 'xml',
    'vssettings': 'xml',
    'vstemplate': 'xml',
    'vxml': 'xml',
    'wixproj': 'xml',
    'wsdl': 'xml',
    'wsf': 'xml',
    'wxi': 'xml',
    'wxl': 'xml',
    'wxs': 'xml',
    'x3d': 'xml',
    'xacro': 'xml',
    'xaml': 'xml',
    'xib': 'xml',
    'xlf': 'xml',
    'xliff': 'xml',
    'xmi': 'xml',
    'xml.dist': 'xml',
    'xproj': 'xml',
    'xsd': 'xml',
    'xspec': 'xml',
    'xul': 'xml',
    'zcml': 'xml',
    'stTheme': 'xml_property_list',
    'tmCommand': 'xml_property_list',
    'tmLanguage': 'xml_property_list',
    'tmPreferences': 'xml_property_list',
    'tmSnippet': 'xml_property_list',
    'tmTheme': 'xml_property_list',
    'xsp-config': 'xpages',
    'xsp.metadata': 'xpages',
    'xpl': 'xproc',
    'xproc': 'xproc',
    'xquery': 'xquery',
    'xq': 'xquery',
    'xql': 'xquery',
    'xqm': 'xquery',
    'xqy': 'xquery',
    'xs': 'xs',
    'xslt': 'xslt',
    'xsl': 'xslt',
    'xojo_code': 'xojo',
    'xojo_menu': 'xojo',
    'xojo_report': 'xojo',
    'xojo_script': 'xojo',
    'xojo_toolbar': 'xojo',
    'xojo_window': 'xojo',
    'xtend': 'xtend',
    'yml': 'yaml',
    'mir': 'yaml',
    'reek': 'yaml',
    'rviz': 'yaml',
    'sublime-syntax': 'yaml',
    'syntax': 'yaml',
    'yaml': 'yaml',
    'yaml-tmlanguage': 'yaml',
    'yaml.sed': 'yaml',
    'yml.mysql': 'yaml',
    'yang': 'yang',
    'yar': 'yara',
    'yara': 'yara',
    'yasnippet': 'yasnippet',
    'y': 'yacc',
    'yacc': 'yacc',
    'zap': 'zap',
    'xzap': 'zap',
    'zil': 'zil',
    'mud': 'zil',
    'zeek': 'zeek',
    'bro': 'zeek',
    'zs': 'zenscript',
    'zep': 'zephir',
    'zig': 'zig',
    'zimpl': 'zimpl',
    'zmpl': 'zimpl',
    'zpl': 'zimpl',
    'desktop': 'desktop',
    'desktop.in': 'desktop',
    'dircolors': 'dircolors',
    'ec': 'ec',
    'eh': 'ec',
    'edn': 'edn',
    'fish': 'fish',
    'mrc': 'mirc_script',
    'mcfunction': 'mcfunction',
    'mu': 'mupad',
    'nanorc': 'nanorc',
    'nc': 'nesc',
    'ooc': 'ooc',
    'rst': 'restructuredtext',
    'rest': 'restructuredtext',
    'rest.txt': 'restructuredtext',
    'rst.txt': 'restructuredtext',
    'sed': 'sed',
    'wdl': 'wdl',
    'wisp': 'wisp',
    'prg': 'xbase',
    'prw': 'xbase'
};
