export const TEST_SYNC_QUEUE = 'TEST_SYNC_QUEUE';

export const TEST_SYNC_CREATE = 'TEST_SYNC_CREATE';
export const TEST_SYNC_UPDATE = 'TEST_SYNC_UPDATE';
export const TEST_SYNC_DELETE = 'TEST_SYNC_DELETE';

export const TEST_INPUT_SYNC_CREATE = 'TEST_INPUT_SYNC_CREATE';
export const TEST_INPUT_SYNC_UPDATE = 'TEST_INPUT_SYNC_UPDATE';

export const TEST_OUTPUT_SYNC_CREATE = 'TEST_OUTPUT_SYNC_CREATE';
export const TEST_OUTPUT_SYNC_UPDATE = 'TEST_OUTPUT_SYNC_UPDATE';
