export const STATIC_CORRECTOR_SYNC_QUEUE = 'STATIC_CORRECTOR_SYNC_QUEUE';
export const STATIC_CORRECTOR_SYNC_CREATE = 'STATIC_CORRECTOR_SYNC_CREATE';
export const STATIC_CORRECTOR_SYNC_UPDATE = 'STATIC_CORRECTOR_SYNC_UPDATE';
export const STATIC_CORRECTOR_SYNC_DELETE = 'STATIC_CORRECTOR_SYNC_DELETE';
