export const TEMPLATE_SYNC_QUEUE = 'TEMPLATE_SYNC_QUEUE';
export const TEMPLATE_SYNC_CREATE = 'TEMPLATE_SYNC_CREATE';
export const TEMPLATE_SYNC_UPDATE = 'TEMPLATE_SYNC_UPDATE';
export const TEMPLATE_SYNC_DELETE = 'TEMPLATE_SYNC_DELETE';
