export const CHALLENGE_SYNC_QUEUE = 'CHALLENGE_SYNC_QUEUE';
export const CHALLENGE_SYNC_CREATE = 'CHALLENGE_SYNC_CREATE';
export const CHALLENGE_SYNC_UPDATE = 'CHALLENGE_SYNC_UPDATE';
export const CHALLENGE_SYNC_DELETE = 'CHALLENGE_SYNC_DELETE';
