export const RULE_SYNC_QUEUE = 'RULE_SYNC_QUEUE';
export const RULE_SYNC_CREATE = 'RULE_SYNC_CREATE';
export const RULE_SYNC_UPDATE = 'RULE_SYNC_UPDATE';
export const RULE_SYNC_DELETE = 'RULE_SYNC_DELETE';
