export const EMBEDDABLE_SYNC_QUEUE = 'EMBEDDABLE_SYNC_QUEUE';
export const EMBEDDABLE_SYNC_CREATE = 'EMBEDDABLE_SYNC_CREATE';
export const EMBEDDABLE_SYNC_UPDATE = 'EMBEDDABLE_SYNC_UPDATE';
export const EMBEDDABLE_SYNC_DELETE = 'EMBEDDABLE_SYNC_DELETE';
