export const DYNAMIC_CORRECTOR_SYNC_QUEUE = 'DYNAMIC_CORRECTOR_SYNC_QUEUE';
export const DYNAMIC_CORRECTOR_SYNC_CREATE = 'DYNAMIC_CORRECTOR_SYNC_CREATE';
export const DYNAMIC_CORRECTOR_SYNC_UPDATE = 'DYNAMIC_CORRECTOR_SYNC_UPDATE';
export const DYNAMIC_CORRECTOR_SYNC_DELETE = 'DYNAMIC_CORRECTOR_SYNC_DELETE';
