export const REWARD_SYNC_QUEUE = 'REWARD_SYNC_QUEUE';
export const REWARD_SYNC_CREATE = 'REWARD_SYNC_CREATE';
export const REWARD_SYNC_UPDATE = 'REWARD_SYNC_UPDATE';
export const REWARD_SYNC_DELETE = 'REWARD_SYNC_DELETE';
