export const SKELETON_SYNC_QUEUE = 'SKELETON_SYNC_QUEUE';
export const SKELETON_SYNC_CREATE = 'SKELETON_SYNC_CREATE';
export const SKELETON_SYNC_CREATE_FILE = 'SKELETON_SYNC_CREATE_FILE';
export const SKELETON_SYNC_UPDATE = 'SKELETON_SYNC_UPDATE';
export const SKELETON_SYNC_UPDATE_FILE = 'SKELETON_SYNC_UPDATE_FILE';
export const SKELETON_SYNC_DELETE = 'SKELETON_SYNC_DELETE';
