export const SOLUTION_SYNC_QUEUE = 'SOLUTION_SYNC_QUEUE';
export const SOLUTION_SYNC_CREATE = 'SOLUTION_SYNC_CREATE';
export const SOLUTION_SYNC_UPDATE = 'SOLUTION_SYNC_UPDATE';
export const SOLUTION_SYNC_DELETE = 'SOLUTION_SYNC_DELETE';
