export const LIBRARY_SYNC_QUEUE = 'LIBRARY_SYNC_QUEUE';
export const LIBRARY_SYNC_CREATE = 'LIBRARY_SYNC_CREATE';
export const LIBRARY_SYNC_UPDATE = 'LIBRARY_SYNC_UPDATE';
export const LIBRARY_SYNC_DELETE = 'LIBRARY_SYNC_DELETE';
