export const LEADERBOARD_SYNC_QUEUE = 'LEADERBOARD_SYNC_QUEUE';
export const LEADERBOARD_SYNC_CREATE = 'LEADERBOARD_SYNC_CREATE';
export const LEADERBOARD_SYNC_UPDATE = 'LEADERBOARD_SYNC_UPDATE';
export const LEADERBOARD_SYNC_DELETE = 'LEADERBOARD_SYNC_DELETE';
