export const INSTRUCTION_SYNC_QUEUE = 'INSTRUCTION_SYNC_QUEUE';
export const INSTRUCTION_SYNC_CREATE = 'INSTRUCTION_SYNC_CREATE';
export const INSTRUCTION_SYNC_CREATE_FILE = 'INSTRUCTION_SYNC_CREATE_FILE';
export const INSTRUCTION_SYNC_UPDATE = 'INSTRUCTION_SYNC_UPDATE';
export const INSTRUCTION_SYNC_UPDATE_FILE = 'INSTRUCTION_SYNC_UPDATE_FILE';
export const INSTRUCTION_SYNC_DELETE = 'INSTRUCTION_SYNC_DELETE';
