export const PROJECT_TOKEN = 'ProjectRepositoryToken';
export const PERMISSION_TOKEN = 'PermissionRepositoryToken';

export const PROJECT_SYNC_QUEUE = 'PROJECT_SYNC_QUEUE';
export const PROJECT_SYNC_CREATE_REPO = 'PROJECT_SYNC_CREATE_REPO';
export const PROJECT_SYNC_CREATE_METADATA = 'PROJECT_SYNC_CREATE_METADATA';
export const PROJECT_SYNC_UPDATE_REPO = 'PROJECT_SYNC_UPDATE_REPO';
export const PROJECT_SYNC_UPDATE_METADATA = 'PROJECT_SYNC_UPDATE_METADATA';
export const PROJECT_SYNC_DELETE_REPO = 'PROJECT_SYNC_DELETE_REPO';
