export const STATEMENT_SYNC_QUEUE = 'STATEMENT_SYNC_QUEUE';
export const STATEMENT_SYNC_CREATE = 'STATEMENT_SYNC_CREATE';
export const STATEMENT_SYNC_CREATE_FILE = 'STATEMENT_SYNC_CREATE_FILE';
export const STATEMENT_SYNC_UPDATE = 'STATEMENT_SYNC_UPDATE';
export const STATEMENT_SYNC_UPDATE_FILE = 'STATEMENT_SYNC_UPDATE_FILE';
export const STATEMENT_SYNC_DELETE = 'STATEMENT_SYNC_DELETE';
