export const GAMIFICATION_LAYER_TOKEN = 'GamificationLayerRepositoryToken';

export const GAMIFICATION_LAYER_SYNC_QUEUE = 'GAMIFICATION_LAYER_SYNC_QUEUE';
export const GAMIFICATION_LAYER_SYNC_CREATE = 'GAMIFICATION_LAYER_SYNC_CREATE';
export const GAMIFICATION_LAYER_SYNC_UPDATE = 'GAMIFICATION_LAYER_SYNC_UPDATE';
export const GAMIFICATION_LAYER_SYNC_DELETE = 'GAMIFICATION_LAYER_SYNC_DELETE';
